## sets super user level permissions, needed to execute this build with travis-ci
sudo: required

## tells travis ci that it needs to build a docker container
services:
  - docker

before_scripts:
  - docker build -t escobard/docker-courses -f Dockerfile.dev .

## tells the service to run a script, after the docker container has been built
scripts:
  - docker run escobard/docker-courses npm run test -- --coverage