version: '3'
services:
  web:
    build:
      ## specifies where the source files are for the service, in this casae this directory
      context: .
      ## specifies which dockerfile to use to create the service
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    ## specifies volumes, and what folders to grab / ignore
    volumes:
      ### not specifiing a folder:containerFolder argument, explicitely refers to working directory of docker folder
      - /usr/section6-ui/node_modules
      ### this creates a volume reference for the local parent directory
      ### this means any time the local directory is updated, the running docker container is updated with these files too
      - .:/usr/section6-ui